# Generated by Django 5.0.4 on 2024-04-24 15:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("modificado_em", models.DateTimeField(auto_now_add=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome da Pessoa"),
                ),
                (
                    "rede_social",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FACEBOOK", "Facebook"),
                            ("INSTAGRAM", "Instagram"),
                            ("WHATSAPP", "Whatsapp"),
                        ],
                        max_length=30,
                        null=True,
                        verbose_name="Rede Social (opcional)",
                    ),
                ),
                ("relato", models.TextField()),
                (
                    "contato",
                    models.CharField(max_length=50, verbose_name="Contato avaliador"),
                ),
            ],
            options={
                "verbose_name": "Avaliações",
                "ordering": ("nome",),
            },
        ),
    ]
