# Generated by Django 5.0.4 on 2024-04-24 12:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categoria", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Imagem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("modificado_em", models.DateTimeField(auto_now_add=True)),
                ("ativo", models.BooleanField(default=True)),
                ("titulo", models.CharField(max_length=20, verbose_name="Titulo")),
                ("arquivo", models.FileField(upload_to="imagens")),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="categoria.categoria",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
