# Generated by Django 5.0.4 on 2024-04-25 11:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sobre", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sobre",
            old_name="crenca",
            new_name="origem",
        ),
        migrations.RemoveField(
            model_name="sobre",
            name="valores",
        ),
        migrations.CreateModel(
            name="Crencas",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("modificado_em", models.DateTimeField(auto_now_add=True)),
                ("ativo", models.BooleanField(default=True)),
                ("crenca", models.CharField(max_length=256)),
                (
                    "sobre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="sobre.sobre"
                    ),
                ),
            ],
            options={
                "verbose_name": "Crenças",
                "verbose_name_plural": "Crenças",
                "ordering": ("crenca",),
            },
        ),
        migrations.CreateModel(
            name="Valores",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("modificado_em", models.DateTimeField(auto_now_add=True)),
                ("ativo", models.BooleanField(default=True)),
                ("valor", models.CharField(max_length=256)),
                (
                    "sobre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="sobre.sobre"
                    ),
                ),
            ],
            options={
                "verbose_name": "Valores",
                "verbose_name_plural": "Valores",
                "ordering": ("valor",),
            },
        ),
    ]
