# Generated by Django 5.0.4 on 2024-04-23 17:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("modificado_em", models.DateTimeField(auto_now_add=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("IMAGEM", "Imagem"), ("DESTAQUE", "Destaque")],
                        max_length=20,
                        verbose_name="Tipo de Categoria",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=50, verbose_name="Nome da Categoria"),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ("nome",),
            },
        ),
    ]
