# Generated by Django 5.0.4 on 2024-04-24 12:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destaque",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("modificado_em", models.DateTimeField(auto_now_add=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "titulo",
                    models.CharField(max_length=100, verbose_name="Titulo do Destaque"),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Descricao do Destaque",
                    ),
                ),
            ],
            options={
                "verbose_name": "Destaque",
                "verbose_name_plural": "Destaques",
                "ordering": ("tipo",),
            },
        ),
    ]
