# Generated by Django 5.0.4 on 2024-04-25 19:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categoria", "0002_alter_categoria_tipo"),
        ("imagem", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Destaque",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("modificado_em", models.DateTimeField(auto_now_add=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "titulo",
                    models.CharField(max_length=100, verbose_name="Titulo do Destaque"),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Descricao do Destaque",
                    ),
                ),
                (
                    "imagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="imagem.imagem",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="categoria.categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Destaque",
                "verbose_name_plural": "Destaques",
                "ordering": ("tipo",),
            },
        ),
    ]
