# Generated by Django 5.0.4 on 2024-04-24 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categoria", "0001_initial"),
        ("destaque", "0001_initial"),
        ("imagem", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="destaque",
            name="imagem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="imagem.imagem"
            ),
        ),
        migrations.AddField(
            model_name="destaque",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="categoria.categoria"
            ),
        ),
    ]
