# Generated by Django 5.0.4 on 2024-04-24 15:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categoria", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("modificado_em", models.DateTimeField(auto_now_add=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "titulo",
                    models.CharField(max_length=100, verbose_name="Título do Contato"),
                ),
                (
                    "observacao",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Observação do contato",
                    ),
                ),
                (
                    "contato",
                    models.CharField(
                        max_length=256, verbose_name="Contato(email, telefone, link)"
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="categoria.categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contato",
                "verbose_name_plural": "Contatos",
                "ordering": ("titulo",),
            },
        ),
    ]
